os: linux
language: python
python: "3.6"
addons: 
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['anaconda']


before_script:
 - conda -y update conda
 - conda create -y -n cc python=3.6 anaconda || true
 - conda activate cc
 - conda install -y tensorflow setuptools seaborn mpi4py cloudpickle joblib tqdm
    
script:
   - conda activate cc
   - pip install -e .
   - cd gym
   - pip install -e .
   - cd ../PycoGYM/gym_pyco
   - pip install -e .
   - cd ../..
   - python spinup/run.py ppo_pyco --env warehouse_manager-v0 --num_cpu 1
   - ls -R
   

cache:
  directories:
    - '$HOME/anaconda3'


